### ISSUE TITLE
How edit php.ini?

### ISSUE THREAD

**Issue by parbleux** [erpushpinderrana/dockerize-existing-drupal-project#10]
First of all thank you very much for this code.
I'd like to know how can I edit the php settings in php.ini.

**Comment by pushpinderchauhan** [comment]
You have two options to edit the php.ini. 

One you can edit the php.ini by jumping into the PHP container using the `docker exec` command as mentioned in the [README.md](https://github.com/erpushpinderrana/dockerize-existing-drupal-project/tree/development#detailed-explanation) Once you are inside the container then access it using `/usr/local/etc/php/php.ini` and edit it.

The second option is to put your local custom `php.ini` and copy it over to apache. You can refer to the [development branch ](https://github.com/erpushpinderrana/dockerize-existing-drupal-project/tree/development)for this where we have custom `php.ini` in the [php](https://github.com/erpushpinderrana/dockerize-existing-drupal-project/tree/development/php) folder.

**Comment by parbleux** [comment]
Thank you very much.
