### ISSUE TITLE
Window issue - Drive has not shared, cannot create container

### ISSUE THREAD

**Issue by aaravrana** [erpushpinderrana/dockerize-existing-drupal-project#5]
Tried to setup it on my Window Laptop but couldn't create it successfully. I was getting below issue. Any quick help would be really appreciated.

> Error: for PHP cannot create container for service.php: drive has not been shared.

**Comment by pushpinderchauhan** [comment]
Looks like a volume mounting issue. You should enable the drive that you want to make available to your containers. Just found a good forum - https://docs.microsoft.com/en-us/archive/blogs/stevelasker/configuring-docker-for-windows-volumes

Hope it helps!
